# -*- coding: utf-8 -*-
"""Weather_forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Trv_Gdek0q7KUSd4X-Uyy7DbrR7RRl6j
"""

import pandas as pd

"""#Download Dataset"""

india = pd.read_csv("/content/4109917.csv")
japan= pd.read_csv("/content/4112203.csv")

"""#Data Understanding and Cleaning"""

india.info()

japan.info()

prcp_unique_india = india["PRCP_ATTRIBUTES"].unique()
print(prcp_unique_india)
prcp_unique_japan = japan["PRCP_ATTRIBUTES"].unique()
print(prcp_unique_japan)
tavg__unique_india = india["TAVG_ATTRIBUTES"].unique()
print(tavg__unique_india)
tavg__unique_japan = japan["TAVG_ATTRIBUTES"].unique()
print(tavg__unique_japan)
tmin__unique_india = india["TMIN_ATTRIBUTES"].unique()
print(tmin__unique_india)
tmin__unique_japan = japan["TMIN_ATTRIBUTES"].unique()
print(tmin__unique_japan)
tmax__unique_india = india["TMAX_ATTRIBUTES"].unique()
print(tmax__unique_india)
tmax__unique_japan = japan["TMAX_ATTRIBUTES"].unique()
print(tmax__unique_japan)
snwd_unique_japan = japan["SNWD_ATTRIBUTES"].unique()
print(snwd_unique_japan)

"""# Attribute Codes in NOAA GHCN Data

Each attribute has the form:

- **Measurement Flag** → how the value was measured/derived.  
- **Quality Flag** → if the value failed QC checks.  
- **Source Flag** → where the data came from.  

---

## Meaning of Common Flags

**Measurement Flags**
- B = Two 12-hour totals (derived)  
- D = Incomplete daily total  
- H = Highest hourly temp  
- I = Interpolated  
- G = Generated/fill  

**Quality Flags**
- (blank) = Passed QC  
- O = Outlier  
- I = Internal consistency fail  
- G = Gap check fail  
- K = Streak/frequency fail  

**Source Flags**
- S = GSOD  
- I = ISH  
- G = COOP  
- K = Automated weather stations  
- O = Other official sources  

---

## Good vs Bad Codes (from India & Japan datasets)

**✅ Good**
- `,,S` (clean GSOD)  
- `,,I` (clean ISH)  
- `,S,S` (valid, flagged by source)  
- `H,,S` (valid highest hourly temp)  

**⚠️ Borderline (use with caution)**
- `B,,S` (two 12-hour totals)  
- `D,,S` (incomplete daily total)  

**❌ Bad (drop or flag)**
- `,O,S` (outlier)  
- `,I,S` (internal consistency fail)  
- `,G,S` (gap fail)  
- `B,K,S` (derived + streak fail)  
- `,K,S` (streak fail)  
- `,,G` (gap fail)  
- `,I,G` (interpolated + gap fail)  
- `,I,I` (interpolated + ISH)  
- `nan` (missing)  

"""

import pandas as pd

# Define categories

good_flags = {"", ",,S", ",,I", ",S,S", "H,,S"}
borderline_flags = {"B,,S", "D,,S", ",W,S"}
bad_flags = {",O,S", ",I,S", ",G,S", "B,K,S", ",K,S", ",,G", ",I,G", ",I,I"}

def classify_attribute(value):
    """Classify NOAA attribute codes into Good, Borderline, or Bad."""
    if pd.isna(value):
        return "Bad"   # treat missing as bad
    if value in good_flags:
        return "Good"
    elif value in borderline_flags:
        return "Borderline"
    elif value in bad_flags:
        return "Bad"
    else:
        return "Unknown"  # in case new codes appear

# Example: classify attributes in India dataset
india["PRCP_quality"] = india["PRCP_ATTRIBUTES"].apply(classify_attribute)
india["TAVG_quality"] = india["TAVG_ATTRIBUTES"].apply(classify_attribute)
india["TMIN_quality"] = india["TMIN_ATTRIBUTES"].apply(classify_attribute)
india["TMAX_quality"] = india["TMAX_ATTRIBUTES"].apply(classify_attribute)
india["SNWD_quality"] = india["SNWD_ATTRIBUTES"].apply(classify_attribute)
# Same for Japan dataset
japan["PRCP_quality"] = japan["PRCP_ATTRIBUTES"].apply(classify_attribute)
japan["TAVG_quality"] = japan["TAVG_ATTRIBUTES"].apply(classify_attribute)
japan["TMIN_quality"] = japan["TMIN_ATTRIBUTES"].apply(classify_attribute)
japan["TMAX_quality"] = japan["TMAX_ATTRIBUTES"].apply(classify_attribute)
japan["SNWD_quality"] = japan["SNWD_ATTRIBUTES"].apply(classify_attribute)

# Quick summary
print(india["PRCP_quality"].value_counts())
print(japan["PRCP_quality"].value_counts())

# Function to count quality per station for each attribute, sorted by Good
def count_quality_per_station(df, attr_list):
    results = {}
    for attr in attr_list:
        quality_col = f"{attr}_quality"
        if quality_col not in df.columns:
            continue
        # Count per station
        counts = df.groupby("NAME")[quality_col].value_counts().unstack(fill_value=0)
        # Ensure all categories exist
        for cat in ["Good", "Borderline", "Bad"]:
            if cat not in counts.columns:
                counts[cat] = 0
        # Sort by Good descending
        counts = counts.sort_values(by="Good", ascending=False)
        results[attr] = counts
    return results

# Attributes we care about
attributes = ["PRCP", "TAVG", "TMIN", "TMAX","SNWD"]

# Get counts for India and Japan
india_counts = count_quality_per_station(india, attributes)
japan_counts = count_quality_per_station(japan, attributes)

# Show results
for attr, table in india_counts.items():
    print(f"\nIndia – {attr} Quality Counts per Station (sorted by Good):")
    display(table)

for attr, table in japan_counts.items():
    print(f"\nJapan – {attr} Quality Counts per Station (sorted by Good):")
    display(table)

def get_top_stations(df, attr, top_n=10):
    """Return top N stations with most Good values for a given attribute."""
    quality_col = f"{attr}_quality"
    # Count Good per station
    good_counts = df[df[quality_col] == "Good"].groupby("STATION").size().sort_values(ascending=False)
    top_stations = good_counts.head(top_n).index
    return df[df["STATION"].isin(top_stations)]

# =============================
# India Datasets
# =============================

# Heavy Rainfall (PRCP, Top 10 stations)
india_rainfall = get_top_stations(india, "PRCP", top_n=10)[
    ["STATION", "NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "PRCP"]
]

# Heatstorm/Coldstorm (TAVG, Top 10 stations)
india_temp = get_top_stations(india, "TAVG", top_n=10)[
    ["STATION", "NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "TAVG", "TMIN", "TMAX"]
]

# =============================
# Japan Datasets
# =============================

# Heavy Rainfall (PRCP, Top 10 stations)
japan_rainfall = get_top_stations(japan, "PRCP", top_n=10)[
    ["STATION", "NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "PRCP"]
]

# Heatstorm/Coldstorm (TAVG, Top 10 stations)
japan_temp = get_top_stations(japan, "TAVG", top_n=10)[
    ["STATION", "NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "TAVG", "TMIN", "TMAX"]
]

# Snowstorm (SNWD, Top 5 stations)
japan_snow = get_top_stations(japan, "SNWD", top_n=5)[
    ["STATION", "NAME", "LATITUDE", "LONGITUDE", "ELEVATION", "DATE", "SNWD"]
]

# =============================
# Preview
# =============================
print("India Rainfall:", india_rainfall.shape)
print("India Temp:", india_temp.shape)
print("Japan Rainfall:", japan_rainfall.shape)
print("Japan Temp:", japan_temp.shape)
print("Japan Snow:", japan_snow.shape)

a = india_rainfall["NAME"].unique()
print(a)
b = india_temp["NAME"].unique()
print(b)
c = japan_rainfall["NAME"].unique()
print(c)
d = japan_temp["NAME"].unique()
print(d)
e = japan_snow["NAME"].unique()
print(e)

japan.groupby("NAME")[["LATITUDE","LONGITUDE","ELEVATION"]].nunique()

import pandas as pd

# ======================
# CONFIG
# ======================
start_date = "1990-01-01"
end_date = "2025-07-31"
full_range = pd.date_range(start_date, end_date, freq="D")

# ======================
# FUNCTION TO CLEAN DATASET
# ======================
def resample_station(df, value_cols):
    """
    df: dataframe with columns including STATION, NAME, LATITUDE, LONGITUDE, ELEVATION, DATE, ...value_cols
    value_cols: list of weather columns to fill (e.g., ["PRCP"], ["TAVG","TMIN","TMAX"])
    """
    df["DATE"] = pd.to_datetime(df["DATE"])
    filled_groups = []

    for station, g in df.groupby("STATION"):
        # --- metadata ---
        station_meta = {
            "STATION": station,
            "NAME": g["NAME"].iloc[0],
            "LATITUDE": g["LATITUDE"].iloc[0],
            "LONGITUDE": g["LONGITUDE"].iloc[0],
            "ELEVATION": g["ELEVATION"].iloc[0],
        }

        # --- reindex to full daily range 1990-2025 ---
        g = g.set_index("DATE").sort_index()
        g = g.reindex(full_range)

        # --- fill numeric weather values ---
        for col in value_cols:
            if col in g.columns:
                if col in ["PRCP", "SNWD"]:
                    g[col] = g[col].fillna(0)  # missing = 0
                else:  # TAVG, TMIN, TMAX
                    g[col] = g[col].interpolate(method="time").bfill().ffill()

        # --- reset index ---
        g = g.reset_index().rename(columns={"index": "DATE"})

        # --- add metadata ---
        for k, v in station_meta.items():
            g[k] = v

        filled_groups.append(g)

    return pd.concat(filled_groups, ignore_index=True)

# ======================
# APPLY TO EACH DATASET
# ======================

# India Rainfall
india_rainfall_clean = resample_station(india_rainfall, value_cols=["PRCP"])

# India Temperature
india_temp_clean = resample_station(india_temp, value_cols=["TAVG", "TMIN", "TMAX"])

# Japan Rainfall
japan_rainfall_clean = resample_station(japan_rainfall, value_cols=["PRCP"])

# Japan Temperature
japan_temp_clean = resample_station(japan_temp, value_cols=["TAVG", "TMIN", "TMAX"])

# Japan Snowfall
japan_snow_clean = resample_station(japan_snow, value_cols=["SNWD"])


print("✅ All datasets cleaned, filled, and saved.")

india_rainfall_clean.info()

india_rainfall_clean.to_csv("India_Rainfall_Clean.csv", index=False)
india_temp_clean.to_csv("India_Temp_Clean.csv", index=False)
japan_rainfall_clean.to_csv("Japan_Rainfall_Clean.csv", index=False)
japan_temp_clean.to_csv("Japan_Temp_Clean.csv", index=False)
japan_snow_clean.to_csv("Japan_Snow_Clean.csv", index=False)

print("✅ All datasets cleaned and saved.")

japan_snow_clean

"""#Exploratory Data Analysis"""

import matplotlib.pyplot as plt

india_rainfall_clean["Month"] = india_rainfall_clean["DATE"].dt.month

for station_name, g in india_rainfall_clean.groupby("NAME"):
    monthly_mean = g.groupby("Month")["PRCP"].mean()

    plt.figure(figsize=(10,5))
    plt.plot(monthly_mean.index, monthly_mean.values, marker='o', color='blue')
    plt.title(f"Monthly Average Rainfall - {station_name}")
    plt.xlabel("Month")
    plt.ylabel("PRCP (mm)")
    plt.xticks(range(1,13))
    plt.grid(alpha=0.3)
    plt.show()

india_temp_clean["Month"] = india_temp_clean["DATE"].dt.month

for station_name, g in india_temp_clean.groupby("NAME"):
    monthly_mean = g.groupby("Month")["TAVG"].mean()

    plt.figure(figsize=(10,5))
    plt.plot(monthly_mean.index, monthly_mean.values, marker='o', color='red')
    plt.title(f"Monthly Average Temperature - {station_name}")
    plt.xlabel("Month")
    plt.ylabel("TAVG (°C)")
    plt.xticks(range(1,13))
    plt.grid(alpha=0.3)
    plt.show()

japan_snow_clean["Month"] = japan_snow_clean["DATE"].dt.month

for station_name, g in japan_snow_clean.groupby("NAME"):
    monthly_mean = g.groupby("Month")["SNWD"].mean()

    plt.figure(figsize=(10,5))
    plt.plot(monthly_mean.index, monthly_mean.values, marker='o', color='cyan')
    plt.title(f"Monthly Average Snow Depth - {station_name}")
    plt.xlabel("Month")
    plt.ylabel("SNWD (cm)")
    plt.xticks(range(1,13))
    plt.grid(alpha=0.3)
    plt.show()

# Maximum daily precipitation in India
max_prcp_value = india_rainfall_clean["PRCP"].max()
max_prcp_row = india_rainfall_clean[india_rainfall_clean["PRCP"] == max_prcp_value]

print(f"Highest daily precipitation: {max_prcp_value} mm")
print("Details of that day:")
print(max_prcp_row)

max_prcp_japan = japan_rainfall_clean["PRCP"].max()
max_prcp_row_japan = japan_rainfall_clean[japan_rainfall_clean["PRCP"] == max_prcp_japan]

print(f"Highest daily precipitation in Japan: {max_prcp_japan} mm")
print(max_prcp_row_japan)

# Monthly mean for all stations
monthly_mean = india_rainfall_clean.groupby(india_rainfall_clean["DATE"].dt.month)["PRCP"].mean()

plt.figure(figsize=(10,5))
plt.plot(monthly_mean.index, monthly_mean.values, marker='o', color='blue')
plt.title("Average Monthly Rainfall (India)")
plt.xlabel("Month")
plt.ylabel("PRCP (mm)")
plt.xticks(range(1,13))
plt.grid(alpha=0.3)
plt.show()

import matplotlib.pyplot as plt


heavy_threshold = india_rainfall_clean["PRCP"].quantile(0.99)
print(f"Heavy rainfall threshold: {heavy_threshold:.2f} mm/day")
# Filter heavy rainfall
heavy_rain = india_rainfall_clean[india_rainfall_clean["PRCP"] > heavy_threshold]

# Count per station
heavy_rain_count = heavy_rain.groupby("NAME").size().sort_values(ascending=False)
print(heavy_rain_count)


plt.figure(figsize=(12,6))
heavy_rain_count.plot(kind="bar", color="blue")
plt.title(f"Number of Heavy Rainfall Days per Station (>{heavy_threshold:.1f} mm)")
plt.xlabel("Station NAME")
plt.ylabel("Number of Days")
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.show()

# Threshold for heavy snow (example: >20 cm/day)
heavy_snow_threshold = 20

heavy_snow = japan_snow_clean[japan_snow_clean["SNWD"] > heavy_snow_threshold]

# Count heavy snow days per station
heavy_snow_count = heavy_snow.groupby("NAME").size().sort_values(ascending=False)
print(heavy_snow_count)

for station_name, g in heavy_snow.groupby("NAME"):
    plt.figure(figsize=(10,5))
    plt.hist(g["SNWD"], bins=20, color="lightblue", edgecolor="black")
    plt.title(f"Distribution of Heavy Snow Days - {station_name}")
    plt.xlabel("Snow Depth (cm)")
    plt.ylabel("Frequency")
    plt.show()

max_snow_value = japan_snow_clean["SNWD"].max()
max_snow_row = japan_snow_clean[japan_snow_clean["SNWD"] == max_snow_value]

print(f"Maximum daily snow depth: {max_snow_value} cm")
print(max_snow_row)

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

# Add Year and Month columns
india_rainfall_clean["Year"] = india_rainfall_clean["DATE"].dt.year
india_rainfall_clean["Month"] = india_rainfall_clean["DATE"].dt.month

# Choose a color map with 12 distinct colors for the months
colors = cm.tab20(np.arange(12))  # tab20 is colorful and distinguishable

# Loop through each year
for year, g in india_rainfall_clean.groupby("Year"):
    monthly_total = g.groupby("Month")["PRCP"].sum()

    plt.figure(figsize=(6,6))
    plt.pie(
        monthly_total,
        labels=[f"{m}" for m in monthly_total.index],
        autopct='%1.1f%%',
        startangle=90,
        colors=colors
    )
    plt.title(f"Rainfall Distribution per Month - {year}")
    plt.show()

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

# Add Year and Month columns
japan_snow_clean["Year"] = japan_snow_clean["DATE"].dt.year
japan_snow_clean["Month"] = japan_snow_clean["DATE"].dt.month

# Choose a color map with 12 distinct colors for the months
colors = cm.tab20(np.arange(12))  # tab20 is colorful and distinguishable

# Loop through each year
for year, g in japan_snow_clean.groupby("Year"):
    monthly_total = g.groupby("Month")["SNWD"].sum()

    plt.figure(figsize=(6,6))
    plt.pie(
        monthly_total,
        labels=[f"{m}" for m in monthly_total.index],
        autopct='%1.1f%%',
        startangle=90,
        colors=colors
    )
    plt.title(f"Snow Distribution per Month - {year}")
    plt.show()

"""#DATA MODELLING"""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ================================
# LOAD DATA
# ================================
df = pd.read_csv("India_Rainfall_Clean.csv", parse_dates=["DATE"])
df = df.groupby("DATE")["PRCP"].mean().reset_index()
df = df.set_index("DATE")

# Aggregate to monthly mean (lighter than daily)
df_monthly = df.resample("ME").mean()   # 'ME' = month end

# ================================
# TRAIN/TEST SPLIT
# ================================
train = df_monthly[:'2019-12-31']   # 30 years (1990–2019)
test = df_monthly['2020-01-01':'2024-12-31']   # 5 years (2020–2024)

# ================================
# FIT MODEL
# ================================
# Use seasonal period = 12 (monthly seasonality)
model1 = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,12),
                enforce_stationarity=False, enforce_invertibility=False)
results = model1.fit(disp=False)

# ================================
# IN-SAMPLE FORECAST (2015–2025)
# ================================
in_sample_forecast = results.get_prediction(
    start=pd.to_datetime("2015-01-31"),
    end=pd.to_datetime("2024-12-31")
)
in_sample_mean = in_sample_forecast.predicted_mean

# ================================
# OUT-OF-SAMPLE FORECAST (2025–2030)
# ================================
future_forecast = results.get_forecast(steps=5*12)  # 5 years monthly
future_index = pd.date_range(start="2025-01-31", periods=5*12, freq="ME")
future_mean = pd.Series(future_forecast.predicted_mean.values, index=future_index)

# ================================
# PLOT
# ================================
plt.figure(figsize=(14,6))
# Show actual last 10 years
plt.plot(df_monthly['2015-01-01':'2024-12-31'], label="Actual Data", color="black")
# In-sample forecast overlap
plt.plot(in_sample_mean, label="Model Fit (2015–2025)", color="blue")
# Out-of-sample forecast
plt.plot(future_mean, label="Forecast (2025–2030)", color="red", linestyle="--")

# Vertical line marking forecast start
plt.axvline(x=pd.to_datetime("2025-01-31"), color="gray", linestyle="--", label="Forecast Start")

plt.legend()
plt.title("Monthly Rainfall Forecasting")
plt.show()

# ================================
# PRINT FORECAST VALUES 2025–2030
# ================================
print("Forecasted monthly values (2025–2030):")
print(future_mean.head(12))  # first 12 months of 2025

import joblib

# Save the fitted ARIMA model
joblib.dump(model1, "india_rain_sarima_model.pkl")

# If you want to download it to your local machine from Colab
from google.colab import files
files.download("india_rain_sarima_model.pkl")

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ================================
# LOAD DATA
# ================================
df = pd.read_csv("India_Temp_Clean.csv", parse_dates=["DATE"])
df = df.groupby("DATE")["TAVG"].mean().reset_index()
df = df.set_index("DATE")

# Aggregate to monthly mean (lighter than daily)
df_monthly = df.resample("ME").mean()   # 'ME' = month end

# ================================
# TRAIN/TEST SPLIT
# ================================
train = df_monthly[:'2019-12-31']   # 30 years (1990–2019)
test = df_monthly['2020-01-01':'2024-12-31']   # 5 years (2020–2024)

# ================================
# FIT MODEL
# ================================
# Use seasonal period = 12 (monthly seasonality)
model2 = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,12),
                enforce_stationarity=False, enforce_invertibility=False)
results = model2.fit(disp=False)

# ================================
# IN-SAMPLE FORECAST (2015–2025)
# ================================
in_sample_forecast = results.get_prediction(
    start=pd.to_datetime("2015-01-31"),
    end=pd.to_datetime("2024-12-31")
)
in_sample_mean = in_sample_forecast.predicted_mean

# ================================
# OUT-OF-SAMPLE FORECAST (2025–2030)
# ================================
future_forecast = results.get_forecast(steps=5*12)  # 5 years monthly
future_index = pd.date_range(start="2025-01-31", periods=5*12, freq="ME")
future_mean = pd.Series(future_forecast.predicted_mean.values, index=future_index)

# ================================
# PLOT
# ================================
plt.figure(figsize=(14,6))
# Show actual last 10 years
plt.plot(df_monthly['2015-01-01':'2024-12-31'], label="Actual Data", color="black")
# In-sample forecast overlap
plt.plot(in_sample_mean, label="Model Fit (2015–2025)", color="blue")
# Out-of-sample forecast
plt.plot(future_mean, label="Forecast (2025–2030)", color="red", linestyle="--")

# Vertical line marking forecast start
plt.axvline(x=pd.to_datetime("2025-01-31"), color="gray", linestyle="--", label="Forecast Start")

plt.legend()
plt.title("Monthly Temp_Arverage Forecasting")
plt.show()

# ================================
# PRINT FORECAST VALUES 2025–2030
# ================================
print("Forecasted monthly values (2025–2030):")
print(future_mean.head(12))  # first 12 months of 2025

import joblib

# Save the fitted ARIMA model
joblib.dump(model2, "india_temp_avg_sarima_model.pkl")

# If you want to download it to your local machine from Colab
from google.colab import files
files.download("india_temp_avg_sarima_model.pkl")

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ================================
# LOAD DATA
# ================================
df = pd.read_csv("Japan_Rainfall_Clean.csv", parse_dates=["DATE"])
df = df.groupby("DATE")["PRCP"].mean().reset_index()
df = df.set_index("DATE")

# Aggregate to monthly mean (lighter than daily)
df_monthly = df.resample("ME").mean()   # 'ME' = month end

# ================================
# TRAIN/TEST SPLIT
# ================================
train = df_monthly[:'2019-12-31']   # 30 years (1990–2019)
test = df_monthly['2020-01-01':'2024-12-31']   # 5 years (2020–2024)

# ================================
# FIT MODEL
# ================================
# Use seasonal period = 12 (monthly seasonality)
model3 = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,12),
                enforce_stationarity=False, enforce_invertibility=False)
results = model3.fit(disp=False)

# ================================
# IN-SAMPLE FORECAST (2015–2025)
# ================================
in_sample_forecast = results.get_prediction(
    start=pd.to_datetime("2015-01-31"),
    end=pd.to_datetime("2024-12-31")
)
in_sample_mean = in_sample_forecast.predicted_mean

# ================================
# OUT-OF-SAMPLE FORECAST (2025–2030)
# ================================
future_forecast = results.get_forecast(steps=5*12)  # 5 years monthly
future_index = pd.date_range(start="2025-01-31", periods=5*12, freq="ME")
future_mean = pd.Series(future_forecast.predicted_mean.values, index=future_index)

# ================================
# PLOT
# ================================
plt.figure(figsize=(14,6))
# Show actual last 10 years
plt.plot(df_monthly['2015-01-01':'2024-12-31'], label="Actual Data", color="black")
# In-sample forecast overlap
plt.plot(in_sample_mean, label="Model Fit (2015–2025)", color="blue")
# Out-of-sample forecast
plt.plot(future_mean, label="Forecast (2025–2030)", color="red", linestyle="--")

# Vertical line marking forecast start
plt.axvline(x=pd.to_datetime("2025-01-31"), color="gray", linestyle="--", label="Forecast Start")

plt.legend()
plt.title("Monthly Rainfall Forecasting")
plt.show()

# ================================
# PRINT FORECAST VALUES 2025–2030
# ================================
print("Forecasted monthly values (2025–2030):")
print(future_mean.head(12))  # first 12 months of 2025

import joblib

# Save the fitted ARIMA model
joblib.dump(model3, "japan_rainfall_sarima_model.pkl")

# If you want to download it to your local machine from Colab
from google.colab import files
files.download("japan_rainfall_sarima_model.pkl")

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ================================
# LOAD DATA
# ================================
df = pd.read_csv("Japan_Temp_Clean.csv", parse_dates=["DATE"])
df = df.groupby("DATE")["TAVG"].mean().reset_index()
df = df.set_index("DATE")

# Aggregate to monthly mean (lighter than daily)
df_monthly = df.resample("ME").mean()   # 'ME' = month end

# ================================
# TRAIN/TEST SPLIT
# ================================
train = df_monthly[:'2019-12-31']   # 30 years (1990–2019)
test = df_monthly['2020-01-01':'2024-12-31']   # 5 years (2020–2024)

# ================================
# FIT MODEL
# ================================
# Use seasonal period = 12 (monthly seasonality)
model4 = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,12),
                enforce_stationarity=False, enforce_invertibility=False)
results = model4.fit(disp=False)

# ================================
# IN-SAMPLE FORECAST (2015–2025)
# ================================
in_sample_forecast = results.get_prediction(
    start=pd.to_datetime("2015-01-31"),
    end=pd.to_datetime("2024-12-31")
)
in_sample_mean = in_sample_forecast.predicted_mean

# ================================
# OUT-OF-SAMPLE FORECAST (2025–2030)
# ================================
future_forecast = results.get_forecast(steps=5*12)  # 5 years monthly
future_index = pd.date_range(start="2025-01-31", periods=5*12, freq="ME")
future_mean = pd.Series(future_forecast.predicted_mean.values, index=future_index)

# ================================
# PLOT
# ================================
plt.figure(figsize=(14,6))
# Show actual last 10 years
plt.plot(df_monthly['2015-01-01':'2024-12-31'], label="Actual Data", color="black")
# In-sample forecast overlap
plt.plot(in_sample_mean, label="Model Fit (2015–2025)", color="blue")
# Out-of-sample forecast
plt.plot(future_mean, label="Forecast (2025–2030)", color="red", linestyle="--")

# Vertical line marking forecast start
plt.axvline(x=pd.to_datetime("2025-01-31"), color="gray", linestyle="--", label="Forecast Start")

plt.legend()
plt.title("Monthly Temperature Forecasting")
plt.show()

# ================================
# PRINT FORECAST VALUES 2025–2030
# ================================
print("Forecasted monthly values (2025–2030):")
print(future_mean.head(12))  # first 12 months of 2025

import joblib

# Save the fitted ARIMA model
joblib.dump(model4, "japan_temp_avg_sarima_model.pkl")

# If you want to download it to your local machine from Colab
from google.colab import files
files.download("japan_temp_avg_sarima_model.pkl")

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# ================================
# LOAD DATA
# ================================
df = pd.read_csv("Japan_Snow_Clean.csv", parse_dates=["DATE"])
df = df.groupby("DATE")["SNWD"].mean().reset_index()
df = df.set_index("DATE")

# Aggregate to monthly mean (lighter than daily)
df_monthly = df.resample("ME").mean()   # 'ME' = month end

# ================================
# TRAIN/TEST SPLIT
# ================================
train = df_monthly[:'2019-12-31']   # 30 years (1990–2019)
test = df_monthly['2020-01-01':'2024-12-31']   # 5 years (2020–2024)

# ================================
# FIT MODEL
# ================================
# Use seasonal period = 12 (monthly seasonality)
model5 = SARIMAX(train, order=(1,1,1), seasonal_order=(1,1,1,12),
                enforce_stationarity=False, enforce_invertibility=False)
results = model5.fit(disp=False)

# ================================
# IN-SAMPLE FORECAST (2015–2025)
# ================================
in_sample_forecast = results.get_prediction(
    start=pd.to_datetime("2015-01-31"),
    end=pd.to_datetime("2024-12-31")
)
in_sample_mean = in_sample_forecast.predicted_mean

# ================================
# OUT-OF-SAMPLE FORECAST (2025–2030)
# ================================
future_forecast = results.get_forecast(steps=5*12)  # 5 years monthly
future_index = pd.date_range(start="2025-01-31", periods=5*12, freq="ME")
future_mean = pd.Series(future_forecast.predicted_mean.values, index=future_index)

# ================================
# PLOT
# ================================
plt.figure(figsize=(14,6))
# Show actual last 10 years
plt.plot(df_monthly['2015-01-01':'2024-12-31'], label="Actual Data", color="black")
# In-sample forecast overlap
plt.plot(in_sample_mean, label="Model Fit (2015–2025)", color="blue")
# Out-of-sample forecast
plt.plot(future_mean, label="Forecast (2025–2030)", color="red", linestyle="--")

# Vertical line marking forecast start
plt.axvline(x=pd.to_datetime("2025-01-31"), color="gray", linestyle="--", label="Forecast Start")

plt.legend()
plt.title("Monthly Snow Forecasting")
plt.show()

# ================================
# PRINT FORECAST VALUES 2025–2030
# ================================
print("Forecasted monthly values (2025–2030):")
print(future_mean.head(12))  # first 12 months of 2025

